### ISSUE TITLE
Race condition in rf12_canSend()

### ISSUE THREAD

**Issue by jcw** [jcw/jeelib#33]
see discussion at http://openenergymonitor.org/emon/node/1051?page=3

**Comment by JohnOH** [comment]
Umh, did this come to a resolution?

**Comment by CapnBry** [comment]
I wrapped the mode switch in an atomic block and the code has been in production without fail, even in numerous transmitter / receiver environments without any lockups for months and months.
https://github.com/CapnBry/HeaterMeter/blob/master/arduino/libraries/rf12_itplus/rf12_itplus.cpp#L357

I did that and in rf12_sendStart() as well even though theoretically there is a very very low chance of there being an interrupt if the receiver is off. My code is a little different though because it does the IT+ protocol rather than the Jeelab protocol.

**Comment by lettierimarco** [comment]
Hello, we're probably experiencing similar problems.
Like Open Energy Monitor  discussion some of our devices, with no apparent reason, cease to communicate  each other. 
simply electrically restart solves the problem immediatly but is a poor solution.
We would like to avoid this restart obvisuly.
I don't know if it could be interesting: we have noted, using an oscilloscope, that on the question of 0x0000 by the processor (read status) the antenna responds 575 (0000001000111111) that it seems means FIFO EMPTY.
It's quietly difficult to debug this issue, it happens apparently random.
To exclude that our issue is related a race condition in rf12_canSend() we have simply force atomic code like @CapnBry suggested? is that the solution for this issue?

**Comment by CapnBry** [comment]
Hi Marco and Jean Claude, I'm still using the code with ATOMIC_BLOCK()s on `rf12_recvStart`, `rf12_canSend` and `rf12_sendStart` and still have had no lockups on any of my transmitting or receiving nodes in years of operation. The power has gone out a dozen times here over the past few years, but this isn't really an uptime thing as much as it is a eventually-it-will-happen thing. I have 9 modules all communicating with a transmit frequency between 4 seconds and 30 seconds depending on the application.

Oddly enough, I *just* bought an emonTx and put it in service last week. However, I have the RFM69 turned off because I have nothing to receive it @433MHz. I would recommend that you try adding the 3 atomic blocks to your source code Marco and seeing if it fixes your lockup issues (if the code is still relevant now that the source has changed a lot for the RF69).

**Comment by jcw** [comment]
The atomic wrapper looks like an excellent solution.
